export const services = [
  {
    icon: '🌐',
    iconBg: 'rgba(22,163,74,0.1)',
    tag: '// web',
    tagColor: '#16a34a',
    title: 'Website Development',
    desc: 'A professional website that looks great and converts visitors into clients. Fast, mobile-ready, and built around your brand.',
    features: ['Custom design & branding', 'E-commerce & online sales', 'SEO-friendly structure'],
    dotColor: '#16a34a',
  },
  {
    icon: '⚙️',
    iconBg: 'rgba(37,99,235,0.1)',
    tag: '// software',
    tagColor: '#2563eb',
    title: 'Software & Web Apps',
    desc: 'Custom software built around the way your business actually works. We replace slow manual processes with fast, reliable tools.',
    features: ['Process automation', 'Third-party integrations', 'Mobile app development'],
    dotColor: '#2563eb',
  },
  {
    icon: '🔧',
    iconBg: 'rgba(124,58,237,0.1)',
    tag: '// support',
    tagColor: '#7c3aed',
    title: 'Maintenance & Support',
    desc: 'Once we launch, we stay. Your product is always up to date, secure, and running smoothly — without you having to worry about it.',
    features: ['24/7 uptime monitoring', 'Security & performance', 'Fast bug resolution'],
    dotColor: '#7c3aed',
  },
  {
    icon: '🔄',
    iconBg: 'rgba(217,119,6,0.1)',
    tag: '// updates',
    tagColor: '#d97706',
    title: 'Ongoing Updates',
    desc: 'Your business grows — your digital products should too. We roll out new features, improvements, and updates on your schedule.',
    features: ['New feature releases', 'Design improvements', 'Compatibility upgrades'],
    dotColor: '#d97706',
  },
];

export const whyUsItems = [
  { num: '01', color: '#16a34a', title: 'We Understand Your Business', desc: 'We take the time to learn your industry, your goals, and your customers before writing a single line of code. The result? A product that actually solves your problems.' },
  { num: '02', color: '#2563eb', title: 'Always In The Loop', desc: "Weekly updates, clear timelines, and zero surprises. You'll always know exactly where your project stands — from the first meeting to launch day." },
  { num: '03', color: '#7c3aed', title: 'Modern & Future-Proof', desc: 'We use the latest technologies — including AI where it truly helps — so your product is fast, scalable, and ready to grow with your business.' },
  { num: '04', color: '#d97706', title: 'We Stay After Launch', desc: "Most agencies disappear once a project ships. We don't. We're your long-term tech partner — available for support, updates, and whatever comes next." },
];

export const projects = [
  {
    id: 1,
    name: 'AC Services',
    type: 'Business Website',
    typeColor: '#4ade80',
    location: 'London, UK',
    logo: '/images/acs.png',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1400&auto=format&fit=crop',
    description: 'AC Services needed a professional online presence to win more corporate contracts. We built their full website from scratch — giving them a polished, credible digital identity that now works as their best salesperson, 24 hours a day.',
    delivered: [
      'Custom website design & branding',
      'Services showcase with project gallery',
      'Contact & quote request system',
    ],
    quote: 'The process was straightforward and they were very patient with us. We are very pleased with the work done and would definitely recommend them.',
    client: 'AC Services, London',
    url: 'https://acservices-1.onrender.com/',
  },
  {
    id: 2,
    name: 'Superfanbase',
    type: 'Web Platform',
    typeColor: '#60a5fa',
    location: 'Global',
    logo: '/images/superfanbase.png',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1400&auto=format&fit=crop',
    description: 'Superfanbase had a vision for a fan engagement platform but needed a team to bring it to life. We turned their concept into a fully working product — from UX design to a live platform their users genuinely love.',
    delivered: [
      'Product strategy & full UX design',
      'End-to-end platform development',
      'Launch support & post-release iterations',
    ],
    quote: 'Working with Kova was a fantastic experience. Their guidance turned our vision into a functional live product that our users love.',
    client: 'Superfanbase',
    url: 'https://superfanbase.com',
  },
  {
    id: 3,
    name: 'Togethr Social',
    type: 'Social App',
    typeColor: '#a78bfa',
    location: 'Global',
    logo: '/images/togethr.png',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=1400&auto=format&fit=crop',
    description: 'Togethr came to us with an idea for a social platform and no idea where to begin. We helped structure the concept, designed every screen, and built a polished MVP they could confidently show to investors and early users.',
    delivered: [
      'Concept validation & UX architecture',
      'Full MVP design & development',
      'Investor-ready product delivery',
    ],
    quote: 'The Kova team helped us structure our concept, design the interface, and bring it to life. The result was a polished MVP we could present confidently.',
    client: 'Togethr Social',
    url: 'https://togethrsocial.com',
  },
  {
    id: 4,
    name: 'Jesus Antonio',
    type: 'Management System',
    typeColor: '#fbbf24',
    location: 'Spain',
    logo: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=200&auto=format&fit=crop',
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=1400&auto=format&fit=crop',
    description: 'A busy personal trainer who needed to manage clients remotely. We built a custom web platform that handles bookings, tracks progress, and lets him run his entire business from anywhere — no spreadsheets, no missed appointments.',
    delivered: [
      'Client booking & scheduling system',
      'Progress tracking dashboard',
      'Remote session & payment management',
    ],
    quote: 'Kova guided me through everything and made it simple. The final product exceeded my expectations and is now helping me manage all my clients online.',
    client: 'Jesus Antonio, Personal Trainer',
    url: null,
  },
  {
    id: 5,
    name: 'Tokunize',
    type: 'Fintech Platform',
    typeColor: '#f472b6',
    location: 'Global',
    logo: 'https://media.licdn.com/dms/image/v2/D4E0BAQGwarH4Htnnjg/company-logo_200_200/company-logo_200_200/0/1724149874738/tokunize_logo?e=2147483647&v=beta&t=LJ3K44Ud2VPuNqRL7r1d6YI5mJSMLYCGSdNmUpDE6TA',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=1400&auto=format&fit=crop',
    description: 'Tokunize needed to transform a basic MVP into a production-ready fintech platform for asset tokenization. We took their proof of concept and built a robust, scalable system — giving them the confidence to test their business model in the real market.',
    delivered: [
      'Full-stack platform rebuild & scaling',
      'Tokenization engine integration',
      'Cloud deployment on AWS infrastructure',
    ],
    quote: "We started with a simple MVP and with Kova's help we transformed it into a ready-to-go platform. The results have been amazing.",
    client: 'Tokunize',
    url: 'https://www.linkedin.com/company/tokunize/',
  },
  {
    id: 6,
    name: 'VC Clinic',
    type: 'Healthcare Website',
    typeColor: '#34d399',
    location: 'UK',
    logo: '/images/vcclinic.png',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1400&auto=format&fit=crop',
    description: 'VC Clinic needed a website that made patients feel comfortable before they even walked through the door. We built a clean, professional site that communicates their services clearly, highlights their team, and makes booking simple.',
    delivered: [
      'Professional clinic website & branding',
      'Services, team & patient info pages',
      'Appointment contact & booking system',
    ],
    quote: null,
    client: 'VC Clinic',
    url: null,
  },
];

export const faqItems = [
  { q: 'What services do you offer?', a: 'We build websites, web applications, mobile apps, and custom business software. Whether you need a simple landing page or a complex platform, we handle the whole process from design to launch.' },
  { q: 'How long does a project take?', a: 'Most projects are completed within 1 to 3 months, depending on the scope. We share a clear timeline from day one and send you weekly progress updates throughout.' },
  { q: 'How do I know the project is on track?', a: "Every Friday we send a progress update and hold a brief check-in with you. You'll always know what's been done, what's next, and any decisions that need your input." },
  { q: 'Do you offer support after launch?', a: 'Yes — we stay after launch. We offer ongoing support, maintenance, and updates so your product keeps working well and improving over time.' },
  { q: 'Can you add AI features to my product?', a: 'Absolutely. We integrate AI tools where they genuinely save time or improve results — from smart search and chatbots to automated workflows and data insights.' },
  { q: 'What does it cost to get started?', a: 'Every project is different, so we give you a custom quote after a free discovery call. There are no hidden fees — just a clear price for a clear scope of work.' },
];

export const aboutValues = [
  {
    icon: '🤝',
    title: 'Team Work',
    desc: "Every project is a collaboration — between our team and yours. We involve you at every step so the end result is something you're proud of.",
  },
  {
    icon: '✅',
    title: 'Take Ownership',
    desc: "We take full responsibility for what we deliver. If something isn't right, we fix it. No excuses, no finger-pointing — just results.",
  },
  {
    icon: '💡',
    title: 'Work Smart',
    desc: 'We choose the right tools for each problem. That means faster delivery, fewer bugs, and products that are easier to maintain and grow.',
  },
];

export const susInitiatives = [
  {
    icon: '⚡',
    title: 'Energy Efficiency',
    desc: 'We use energy-efficient technology in our workspace and encourage remote work to cut commuting emissions across the board.',
  },
  {
    icon: '♻️',
    title: 'Waste Reduction',
    desc: 'We run a paperless office, recycle wherever possible, and continuously look for ways to reduce the waste our operations generate.',
  },
  {
    icon: '🤝',
    title: 'Sustainable Suppliers',
    desc: 'We choose to work with suppliers and platforms that share our commitment to environmentally responsible business practices.',
  },
  {
    icon: '🌍',
    title: 'Community Engagement',
    desc: 'We support local environmental campaigns and partner with organisations that promote conservation and sustainability education.',
  },
];
